spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://127.0.0.1:9411

  sleuth:
    sampler:
      precentage : 1.0

server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service


