eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: user-service
zipkin:
  base-url: http://127.0.0.1:9411

sleuth:
  sampler:
    precentage : 1.0
